spring.application.name=backend

# PostgreSQL config
spring.datasource.url=jdbc:postgresql://localhost:5432/resto
spring.datasource.username=postgres
spring.datasource.password=JkZ5e&jst2u5LRbz

# JPA settings
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

# CORS settings
app.cors.allowed-origins = http://localhost:4200